spring:
  datasource:
    url: jdbc:h2:mem:H2TEST
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    # uncomment below line if you want to insert data using data.sql file
#    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false