DROP TABLE IF EXISTS FORMDATA;
CREATE TABLE FORMDATA (
form_id INT AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
contact VARCHAR(50) NOT NULL
);